"""empty message

Revision ID: 7e752c621b19
Revises: 
Create Date: 2022-06-29 23:30:27.252058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e752c621b19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('adress', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=True),
    sa.Column('adress', sa.Integer(), nullable=True),
    sa.Column('produto', sa.NullType(), nullable=True),
    sa.Column('quantidade', sa.NullType(), nullable=True),
    sa.ForeignKeyConstraint(['adress'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrega')
    op.drop_table('cliente')
    # ### end Alembic commands ###
